version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "01:00"
    ignore:
      - dependency-name: tailwindcss
        versions:
          - "> 3"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "01:00"
