services:
  app:
    image: luisalejandro/luisalejandro.org:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/luisalejandro-org/app
      - ~/.npm:/home/luisalejandro-org/.npm
    env_file:
      - .env
    environment:
      PORT: 3101
    ports:
      - "3101:3101"