version: "3"
services:
  app:
    image: luisalejandro/luisalejandro.org:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/luisalejandro/app
    env_file:
      - .env
    ports:
      - '3000:3000'